---  
  - name: create database
    mysql_db: name=csit state=present
  - name: create mysql user
    mysql_user:
       name: krishna
       password: Krishna@123
       priv: '*.*:ALL'
       #host_all: yes
       state: present
       login_user: root
       login_password: "{{mysql_root_password}}"
