---
- name: this playbook is to install gunicorn packages
  hosts: localhost
  become: true
  tasks:
    - name: Install python3-pip package
      yum:
        name: python3-pip
        state: present
    - name: Install Gunicorn package
      ansible.builtin.pip:
        name: gunicorn
        executable: pip3
